//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buyer
    {
        public int ID { get; set; }
        public string BuyerID { get; set; }
        public string BuyerName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string ShippingAddress { get; set; }
    }
}
