//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSDataAccessLayer
{
    using System;
    
    public partial class JoinOrderDetailsForAdmin_Result1
    {
        public string BuyerName { get; set; }
        public string ShippingAddress { get; set; }
        public string OrderID { get; set; }
        public string BuyerEmail { get; set; }
        public string OrderItemID { get; set; }
        public Nullable<int> OrderQuantity { get; set; }
        public string OrderStatus { get; set; }
        public string ProductImage { get; set; }
        public string ProductName { get; set; }
        public string ProductWeight { get; set; }
        public string ProductHeight { get; set; }
    }
}
