//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSDataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class OMSdbEntities : DbContext
    {
        public OMSdbEntities()
            : base("name=OMSdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AppAdministrator> AppAdministrators { get; set; }
        public DbSet<Buyer> Buyers { get; set; }
        public DbSet<Table_OrderDetails> Table_OrderDetails { get; set; }
        public DbSet<Table_ProductImage> Table_ProductImage { get; set; }
        public DbSet<Table_ProductsDetails> Table_ProductsDetails { get; set; }
    
        public virtual ObjectResult<JoinOrderDetails_Result1> JoinOrderDetails(string buyerID)
        {
            var buyerIDParameter = buyerID != null ?
                new ObjectParameter("BuyerID", buyerID) :
                new ObjectParameter("BuyerID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JoinOrderDetails_Result1>("JoinOrderDetails", buyerIDParameter);
        }
    
        public virtual ObjectResult<JoinOrderDetailsForAdmin_Result1> JoinOrderDetailsForAdmin()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JoinOrderDetailsForAdmin_Result1>("JoinOrderDetailsForAdmin");
        }
    }
}
