//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMSDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_ProductsDetails
    {
        public int ID { get; set; }
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string ProductWeight { get; set; }
        public string ProductHeight { get; set; }
        public Nullable<int> SKU { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> AvailableQuantity { get; set; }
    }
}
